### ISSUE TITLE
Android minsdk version support

### ISSUE THREAD

**Issue by Firefly35** [yctung/AndroidLibSVM#5]
Hello,
we integrate your android libsvm wrapper in a project where we support android sdk from 19 to upper versions.
Building with your wrapper, we figured out the minsdk version declared is 22.
We tested a modified version of the AndroidManifest.xml provided in your aar release to downgrade minsdk to version 19, without meeting any problem.
Can you tell us if there were any reason to not support android sdk  from 19 to 26 versions ?

If there is no particular issue, could you update the 
AndroidLibSVM/AndroidLibSVM/androidlibsvm/build.gradle file to allow support from the 19 sdk version in minsdk ?

Best regards and thanks for the good work done around libSVM

**Comment by yctung** [comment]
Hi Firefly,

Thank you for mentioning it. It is a mistake to set the minsdk as 22 (it happens when I build the project with the Example app which requires 22 to have some UI elements).

I have reduced the minsdk of the library to 16 and compiled a new aar file in the Release folder. Let me know if it fixes your problem :)

Yu-Chih

**Comment by Firefly35** [comment]
Thanks for the update.
Yes it fixes the (light) inconvenience and avoid to downgrade the version through a "hack" :).

Loïc
